### ISSUE TITLE
Masked attention

### ISSUE THREAD

**Issue by RicardoDominguez** [hyunwoongko/transformer#10]
Hi, 

In `ScaleDotProductAttention.forward`, shouldn't the masked inputs be set to `-inf` rather than 0? So for instance

```
score = score.masked_fill(mask == 0, -np.inf)
```

rather than

```
score = score.masked_fill(mask == 0, -e)
```

This is mentioned in Section 3.2.3 of Vaswani et al.

**Comment by d1024choi** [comment]
I think -inf is correct!!

**Comment by hyunwoongko** [comment]
Okay I will fix this. This code was written in 3~4 years, so I am not very expert of language modeling.
thanks for great issue !

**Comment by hyunwoongko** [comment]
https://github.com/hyunwoongko/transformer/blob/master/models/layers/scale_dot_product_attention.py#L35

Fixed.
