### ISSUE TITLE
Potential bug in the pad mask

### ISSUE THREAD

**Issue by RicardoDominguez** [hyunwoongko/transformer#11]
In the `Transformer` class, `trg_pad_idx` is not used, but rather `src_pad_idx` is used to construct both the source and target pad masks. If `trg_pad_idx != src_pad_idx` this would cause unintended behaviour.

**Comment by hyunwoongko** [comment]
@GJ98 Could you open PR to fix this problem?

**Comment by GJ98** [comment]
@hyunwoongko I open PR!

**Comment by hyunwoongko** [comment]
thanks a lot !
