### ISSUE TITLE
LayerNorm implement

### ISSUE THREAD

**Issue by MrSunCodes** [hyunwoongko/transformer#7]
in the original code，layer-norm：
`out = (x - mean) / (std + self.eps)`
but in formula he give, should be 
`out = (x - mean) / math.sqrt(std + self.eps)`

**Comment by ayaka14732** [comment]
The correct implementation should be:

```diff
 class LayerNorm(nn.Module):
     def __init__(self, d_model, eps=1e-12):
         super(LayerNorm, self).__init__()
         self.gamma = nn.Parameter(torch.ones(d_model))
         self.beta = nn.Parameter(torch.zeros(d_model))
         self.eps = eps
 
     def forward(self, x):
         mean = x.mean(-1, keepdim=True)
-        std = x.std(-1, keepdim=True)
+        var = x.var(-1, unbiased=False, keepdim=True)
         # '-1' means last dimension. 
 
-        out = (x - mean) / (std + self.eps)
+        out = (x - mean) / torch.sqrt(var + self.eps)
         out = self.gamma * out + self.beta
         return out
```

See my BART implementation in [bart-base-jax](https://github.com/ayaka14732/bart-base-jax), especially section 5.2.

**Comment by MrSunCodes** [comment]
> The correct implementation should be:
> 
> ```diff
>  class LayerNorm(nn.Module):
>      def __init__(self, d_model, eps=1e-12):
>          super(LayerNorm, self).__init__()
>          self.gamma = nn.Parameter(torch.ones(d_model))
>          self.beta = nn.Parameter(torch.zeros(d_model))
>          self.eps = eps
>  
>      def forward(self, x):
>          mean = x.mean(-1, keepdim=True)
> -        std = x.std(-1, keepdim=True)
> +        var = x.var(-1, unbiased=False, keepdim=True)
>          # '-1' means last dimension. 
>  
> -        out = (x - mean) / (std + self.eps)
> +        out = (x - mean) / torch.sqrt(var + self.eps)
>          out = self.gamma * out + self.beta
>          return out
> ```
> 
> See my BART implementation in [bart-base-jax](https://github.com/ayaka14732/bart-base-jax), especially section 5.2.

Yes! Your implementation is correct! And my can not run>_<

**Comment by ayaka14732** [comment]
Should not close because the original implementation is also not correct
