### ISSUE TITLE
Reporting a bug during test time

### ISSUE THREAD

**Issue by mediadepp** [hyunwoongko/transformer#9]
@hyunwoongko thanks for your nice implementation. By the way, I wanna point out an issue. 
If you notice, while testing, you are utilising the following code: 

```python
def test_model(num_examples):
    iterator = test_iter
    # model.load_state_dict(torch.load("./saved/model-saved.pt"))

    with torch.no_grad():
        batch_bleu = []
        for i, batch in enumerate(iterator):
            src = batch.src
            trg = batch.trg
            output = model(src, trg[:, :-1])
            ...
```

I guess this part has a significant problem that cannot be ignored. While testing, we don't have any target. The target sentence should be created word by word based on the output of the decoder. You should have a loop for that.  You can take a look at [here][1].

[1]: https://glouppe.github.io/info8010-deep-learning/?p=lecture8.md#39

**Comment by hyunwoongko** [comment]
yes I agree with you. we need to decode (maybe greedy, beam search, ...) output tokens.
this code was written in 3 years before, in that time I was not very familiar with transformer models.
thanks for letting me know

**Comment by AnhLD2610** [comment]
i see the problem too, anyone has right code for evaluate and generate summarize text
